- name: Update System
  apt:
    update_cache: true
    upgrade: full
    cache_valid_time: 3600
    autoclean: true
    autoremove: true

- name: Install Default Applications
  apt:
    name: "{{ default_packages }}"
    state: present
    install_recommends: false

- name: Create Standard Users
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    groups: "{{ item.groups | default(omit) }}"
    create_home: "{{ item.create_home | default(false) }}"
    state: present
  loop: "{{ users }}"

- name: Deploy SSH Public Keys
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', 'id_rsa.pub') | trim }}"
  when: lookup('file', 'id_rsa.pub') is defined
  loop: "{{ ssh_users }}"

- name: Configure Sudo
  copy:
    dest: "/etc/sudoers.d/{{ item }}"
    content: "{{ item }} ALL=(ALL:ALL) NOPASSWD: ALL\n"
    validate: "visudo -cf %s"
    owner: root
    group: root
    mode: '0440'
    backup: true
  loop: "{{ ssh_users }}"


- name: Disable SSH Password Authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication no"
    backup: true
  notify: Restart SSH

- name: Disable SSH Root Login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?PermitRootLogin"
    line: "PermitRootLogin no"
    backup: true
  notify: Restart SSH

- name: Get latest Cinc version
  shell: curl -s https://downloads.cinc.sh/files/stable/cinc/ | grep -oP 'href="\d.*/"' | sort -V | tail -n1 | cut -d '"' -f2 | cut -d'/' -f1
  register: cinc_version_result
  changed_when: false

- name: Set Cinc download URL
  set_fact:
    cinc_url: https://downloads.cinc.sh/files/stable/cinc/{{cinc_version_result.stdout}}/debian/12/cinc_{{cinc_version_result.stdout}}-1_{{ lookup('env', 'architecture') | default('amd64', true) }}.deb
  register: cinc_url_result

- name: Debug Cinc URL
  debug:
    msg: "Get Cinc {{ cinc_version_result.stdout }} from {{ cinc_url }}"

- name: Download cinc-client.deb
  ansible.builtin.get_url:
    url: "{{ cinc_url }}"
    dest: ./cinc-client.deb
    validate_certs: false
    mode: '0644'
  when: cinc_version_result.stdout is defined


- name: Install cinc-client.deb
  ansible.builtin.apt:
    deb: ./cinc-client.deb
    state: present
#
#- name: Install Cinc Client
#  shell: url=$(curl -s https://downloads.cinc.sh/files/stable/cinc/ | grep -oP 'href="\d.*/"' | sort -V | tail -n 1 | awk -F '"' '{print  $2 }' | awk -F '/' '{print  "https://downloads.cinc.sh/files/stable/cinc/" $1 "/debian/12/cinc_" $1 "-1_{{ lookup('env', 'architecture') | default('amd64', true) }}".deb" }') && wget -O ./cinc-client.deb "$url" && dpkg -i ./cinc-client.deb && apt-get install -f -y
#
#  args:
#    creates: /opt/cinc/bin/cinc-client
