default_packages:
  - vim
  - wget
  - sudo
  - net-tools
  - procps

users:
  - { name: "app", create_home: false }
  - { name: "config", groups: ["root", "wheel"], create_home: true }
  - { name: "user", shell: "/bin/bash", groups: ["root", "wheel"], create_home: true }

ssh_users:
  - config
  - user
