---
- name: "Prepare Environment"
  hosts: localhost
  gather_facts: no
  vars:
    os: "local:vztmpl/debian-12-standard_12.7-1_amd64.tar.zst"
    ip: "{{ ip }}"
    id: "{{ id }}"
    terminate: "{{ terminate }}"
    PROXMOX_HOST: "{{ PM_HOST }}"
    PROXMOX_USER: "{{ PROXMOX_USER }}"
    PROXMOX_TOKEN_ID: "{{ PROXMOX_TOKEN_ID }}"
    PROXMOX_TOKEN_SECRET: "{{ PROXMOX_TOKEN_SECRET }}"
  tasks:
    - name: "Check for container"
      community.general.proxmox_vm_info:
        api_host: "{{ PROXMOX_HOST }}"
        api_user: "{{ PROXMOX_USER }}"
        api_token_id: "{{ PROXMOX_TOKEN_ID }}"
        api_token_secret: "{{ PROXMOX_TOKEN_SECRET }}"
        api_port: 8006
        node: "pve"
        vmid: "{{ id }}"
      register: container_info
      delegate_to: localhost
      ignore_errors: yes

    - name: "Set container exists"
      set_fact:
        container_exists: "{{ container_info is success and (container_info.proxmox_vms | length) > 0 }}"

    - name: "Stop container"
      community.general.proxmox:
        api_host: "{{ PROXMOX_HOST }}"
        api_user: "{{ PROXMOX_USER }}"
        api_token_id: "{{ PROXMOX_TOKEN_ID }}"
        api_token_secret: "{{ PROXMOX_TOKEN_SECRET }}"
        api_port: 8006
        vmid: "{{ id }}"
        node: "pve"
        state: stopped
        force: yes
      delegate_to: localhost
      ignore_errors: yes
      when: container_exists and (terminate | bool == true)

    - name: "Remove container"
      community.general.proxmox:
        api_host: "{{ PROXMOX_HOST }}"
        api_user: "{{ PROXMOX_USER }}"
        api_token_id: "{{ PROXMOX_TOKEN_ID }}"
        api_token_secret: "{{ PROXMOX_TOKEN_SECRET }}"
        api_port: 8006
        vmid: "{{ id }}"
        node: "pve"
        state: absent
      delegate_to: localhost
      ignore_errors: yes
      register: removal
      when: container_exists and (terminate | bool == true)

    - name: "Wait for removal"
      wait_for:
        path: "/var/lib/vz/private/{{ id }}"
        state: absent
        timeout: 30
      delegate_to: localhost
      when: container_exists and (terminate | bool == true)

    - name: "Create container"
      community.general.proxmox:
        api_host: "{{ PROXMOX_HOST }}"
        api_user: "{{ PROXMOX_USER }}"
        api_token_id: "{{ PROXMOX_TOKEN_ID }}"
        api_token_secret: "{{ PROXMOX_TOKEN_SECRET }}"
        api_port: 8006
        vmid: "{{ id }}"
        node: "pve"
        hostname: "{{ hostname }}"
        ostemplate: "{{ os }}"
        cores: "{{ cores }}"
        memory: "{{ memory }}"
        pubkey: "{{ lookup('file', '/root/.ssh/id_rsa.pub') | trim }}"
        swap: "{{ swap }}"
        disk: "{{ rootfs }}"
        netif:
          net0: "name=eth0,gw=192.168.178.1,ip={{ ip }}/24,bridge=vmbr0"
        onboot: "{{ boot }}"
        state: present
      delegate_to: localhost

    - name: "Start container"
      community.general.proxmox:
        api_host: "{{ PROXMOX_HOST }}"
        api_user: "{{ PROXMOX_USER }}"
        api_token_id: "{{ PROXMOX_TOKEN_ID }}"
        api_token_secret: "{{ PROXMOX_TOKEN_SECRET }}"
        api_port: 8006
        vmid: "{{ id }}"
        node: "pve"
        state: started
      delegate_to: localhost

    - name: "Wait for SSH"
      wait_for:
        port: 22
        host: "{{ ip }}"
        timeout: 60
      delegate_to: localhost

    - name: "Test config user"
      command: "ssh -o BatchMode=yes -o ConnectTimeout=5 -i /root/.ssh/id_rsa config@{{ ip }} echo success"
      register: ssh_config_test
      failed_when: false
      changed_when: false
      when: container_exists and (terminate | bool == false)

    - name: "Set SSH user"
      set_fact:
        ssh_user: "{{ 'config' if (container_exists and (terminate | bool == false) and (ssh_config_test.rc | default(1)) == 0) else 'root' }}"

    - name: "Add container to inventory dynamically"
      add_host:
        name: container
        ansible_host: "{{ ip }}"
        ansible_user: "{{ ssh_user }}"
        ansible_ssh_private_key_file: /root/.ssh/id_rsa
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

    - name: "Debug SSH user decision"
      debug:
        msg: >
          container_exists: {{ container_exists }}
          terminate: {{ terminate }}
          ssh_config_test.rc: {{ ssh_config_test.rc | default('undefined') }}
          ssh_user: {{ ssh_user }}

    - name: Reset host
      ansible.builtin.known_hosts:
        name: "{{ ip }}"
        state: absent
      delegate_to: localhost
      become: false

- name: "Remote container default configuration"
  hosts: container
  gather_facts: no
  become: true
  tasks:
    - name: "Apply default configuration"
      ansible.builtin.include_role:
        name: base
